spring.application.name=OrderService
server.port = 8002

server.servlet.context-path=/Order
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://localhost:3306/microservices
spring.datasource.username = root
spring.datasource.password = madan
spring.jpa.show-sql=true



eureka.client.service-url.defaultZone=http://localhost:8999/eureka
